### ISSUE TITLE
Help, how to compile step by step

### ISSUE THREAD

**Issue by MateusRodriguesF** [dentaro/haco3puter#1]
Im newbie in these embedded systems programing, can you help me with instructions on how to compile on platformio? how to burn?
Thank you in advance.

**Comment by dentaro** [comment]
Thank you for your question. 
I'm not good at English, so I'm using ChatGPT.
try the following steps, which might help you:

Open Visual Studio Code: To use PlatformIO, you need to open Visual Studio Code.

Set up PlatformIO:

Open Visual Studio Code and select Extensions.
In the search bar, type "PlatformIO" and find PlatformIO IDE.
Click the Install button to install the extension.
Once PlatformIO is installed successfully, restart Visual Studio Code.
Create a PlatformIO project:
In the VSCode terminal, execute pio pkg update to install packages to enable the use of the M5Stack StampS3 board.

Create a new project:
Click on the PlatformIO icon in the sidebar of Visual Studio Code and create a new project.
Press the Create New Project button and set the following:

Name: haco3puter
Board: M5Stack StampS3
Framework: Arduino
Build and upload test:
After preparing the source code, use PlatformIO's build feature to compile and write to the microcontroller to verify if the empty project compiles correctly.
Download the source code for haco3puter and overwrite the following in the empty project:

platformio.ini
lib
src
data (create this folder if it doesn't exist)
Install dependent libraries:
Two dependent libraries, M5GFX and M5unified, will be installed when you perform another write.

Upload the contents of the data folder to SPIFFS:
Under PROJECT TASKS, press Upload Filesystem Image to copy all contents of the data folder to the SPIFFS, which is the file system area.
The file structure within the data folder is listed in the cheat sheet.

By following these steps, you can create a new project with PlatformIO and start developing haco3.

**Comment by dentaro** [comment]
![Cheat sheet](https://github.com/dentaro/haco3puter/assets/77978725/d7df572a-010e-4564-acb7-3d68c7cb6878)

The sample Lua program is located in data/appname/main.lua. By referencing the cheat sheet, you can edit main.lua to create or modify the game. Once you've finished coding, please upload it to SPIFFS again.

Additionally, you can use the built-in editor to edit Lua code and adjust parameters without needing a PC.

We're using Lua 5.3, so please refer to Lua's website for Lua syntax.

Press "~" (Aa+esc) to return to the menu.

Press "OK" to confirm the app selection.

Press "|" to toggle between the editor and execution modes.

In editor mode:

Press "fn" to switch, and the right bar will turn orange.

The mode changes, and you can use the cursor and other features.

Press "Aa" to switch, and the right bar will turn blue.

You can toggle between uppercase and lowercase and perform other tasks.

Enjoy!

**Comment by MateusRodriguesF** [comment]
Thank you very much for your answer, I didn't expect it to be so complete.
With these instructions I will certainly be able to run your project on my cardputer 😁.
Thank you and best wishes!

**Comment by MateusRodriguesF** [comment]
Thank you very much for your answer, I didn't expect it to be so complete.
With these instructions I will certainly be able to run your project on my cardputer 😁.
Thank you and best wishes!
